### ISSUE TITLE
use 'nodeValue' instead of 'balanceValue'

### ISSUE THREAD

**Issue by yongguangl** [PacktPublishing/Learn-Data-Structures-and-Algorithms-with-Golang#2]
https://github.com/PacktPublishing/Learn-Data-Structures-and-Algorithms-with-Golang/blob/c70b1c186ab6f8390d7d142979dac47b90622b8e/Chapter04/avl_tree.go#L61

**Comment by deepesh-packt** [comment]
Hey @yongguangl 
As per your feedback/suggestion, the code has been updated.
Thanks!
