### ISSUE TITLE
Package container is not shown but referenced

### ISSUE THREAD

**Issue by aamchi** [PacktPublishing/Learn-Data-Structures-and-Algorithms-with-Golang#4]
The container package is referenced but it does not exist in this repo.  The first example in the chapter 1 of the book refers to list.go which refers to `container/list`.  

https://github.com/PacktPublishing/Learn-Data-Structures-and-Algorithms-with-Golang/blob/master/Chapter01/list.go#L13

This package does not exist and it doesn't provide a way to continue further.

**Comment by bhagvank** [comment]
please check this link: https://golang.org/pkg/container/list

There is an example shown using the package container/list.
